// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $post_id_ from "./routes/post/[id].tsx";
import * as $post_create from "./routes/post/create.tsx";
import * as $search from "./routes/search.tsx";
import * as $CreatePostForm from "./islands/CreatePostForm.tsx";
import * as $LikeButton from "./islands/LikeButton.tsx";
import * as $ViewToggle from "./islands/ViewToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
    "./routes/post/[id].tsx": $post_id_,
    "./routes/post/create.tsx": $post_create,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/CreatePostForm.tsx": $CreatePostForm,
    "./islands/LikeButton.tsx": $LikeButton,
    "./islands/ViewToggle.tsx": $ViewToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
